name: Update README

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    update-readme:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Update README
          run: python utils/update_readme.py
        - name: Commit changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            if git diff --quiet HEAD; then
                echo "No changes to commit"
            else
                git commit -m "Update README.md"
                git push
            fi