name: Folder Structure Validation

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-structure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Validate folder structure
      run: python utils/validate_folders.py